[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements-railway.txt"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput --clear && echo 'Static files collected:' && ls -la staticfiles/ && gunicorn farmfresh.wsgi:application --bind 0.0.0.0:$PORT --workers 3"
healthcheckPath = "/api/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[deploy.envs]
PYTHON_VERSION = "3.9"
