# Generated by Django 4.2.23 on 2025-08-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('CONSUMER', 'Consumer'), ('OTHERS', 'Others')], default='OTHERS', max_length=20),
        ),
    ]
