# Generated by Django 4.2.23 on 2025-08-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('CONSUMER', 'Consumer'), ('OTHERS', 'Others'), ('BUSINESS', 'Business'), ('DISTRIBUTOR', 'Distributor')], default='OTHERS', max_length=20),
        ),
    ]
