# Generated by Django 4.2.23 on 2025-09-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_userprofile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('CONSUMER', 'Consumer'), ('OTHERS', 'Others'), ('BUSINESS', 'Business'), ('DISTRIBUTOR', 'Distributor'), ('STAFF', 'Staff')], default='OTHERS', max_length=20),
        ),
    ]
