# Generated by Django 4.2.23 on 2025-08-08 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_alter_produce_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produce',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produce',
            name='unit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produce',
            name='variety',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='produce',
            index=models.Index(fields=['available'], name='farmers_pro_availab_a018b9_idx'),
        ),
        migrations.AddIndex(
            model_name='produce',
            index=models.Index(fields=['created_at'], name='farmers_pro_created_a0b9f4_idx'),
        ),
        migrations.AddIndex(
            model_name='produce',
            index=models.Index(fields=['farmer', 'available'], name='farmers_pro_farmer__d93346_idx'),
        ),
    ]
