# Generated by Django 4.2.23 on 2025-08-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_alter_produce_name_alter_produce_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produce/'),
        ),
    ]
