# Generated by Django 4.2.23 on 2025-08-08 21:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_total_price_order_total_amount_and_more'),
        ('farmers', '0004_produce_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produce',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='produce',
            name='total_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FarmerEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='farmers.farmerprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_earnings', to='orders.order')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='farmers.produce')),
            ],
            options={
                'indexes': [models.Index(fields=['farmer', 'status'], name='farmers_far_farmer__9e2e61_idx'), models.Index(fields=['created_at'], name='farmers_far_created_d80dd2_idx')],
            },
        ),
    ]
