# Generated by Django 4.2.23 on 2025-08-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_farmerprofile_total_earnings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='name',
            field=models.CharField(choices=[('TOMATOES', 'Tomatoes'), ('YAM', 'Yam'), ('TATASHE', 'Tatashe'), ('BELL_PEPPER', 'Bell pepper'), ('CAYENNE_PEPPER', 'Cayenne pepper (Sombo & Bawa)'), ('SCOTCH_BONNET', 'Scotch bonnet pepper (Ata rodo)'), ('MAIZE', 'Maize (Corn)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='produce',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('CRATES', 'Crates'), ('BUNCHES', 'Bunches'), ('TUBERS', 'Tubers'), ('SACS', 'Sacs')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='produce',
            constraint=models.UniqueConstraint(fields=('farmer', 'name', 'variety', 'unit'), name='uniq_farmer_produce_variant_unit'),
        ),
    ]
