# Generated by Django 4.2.23 on 2025-08-08 21:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_farmerprofile_total_earnings_and_more'),
        ('orders', '0002_remove_order_total_price_order_total_amount_and_more'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms_days', models.PositiveIntegerField(default=0)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pdf_path', models.CharField(blank=True, help_text='Path to generated PDF invoice', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(help_text='e.g., kg, crate, sack', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name, e.g. 'Weekly tomatoes'", max_length=200)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('next_delivery_date', models.DateField()),
                ('priority', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('agreed_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='account_manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='account_manager_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='account_manager_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='branding_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('CATERER', 'Caterer'), ('HOTEL', 'Hotel'), ('SUPERMARKET', 'Supermarket'), ('LARGE_BUYER', 'Large Buyer')], default='LARGE_BUYER', max_length=30),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='credit_terms_days',
            field=models.PositiveIntegerField(default=0, help_text='0 = prepaid, 7/30 = net terms'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='packaging_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='support_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='support_whatsapp',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['user'], name='business_bu_user_id_df7cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['company'], name='business_bu_company_350d05_idx'),
        ),
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['business_type'], name='business_bu_busines_a43dbd_idx'),
        ),
        migrations.AddField(
            model_name='contractorderitem',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.contractorder'),
        ),
        migrations.AddField(
            model_name='contractorderitem',
            name='produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.produce'),
        ),
        migrations.AddField(
            model_name='contractorder',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_orders', to='business.businessprofile'),
        ),
        migrations.AddField(
            model_name='businesspricingtier',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Null = global tier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='business.businessprofile'),
        ),
        migrations.AddField(
            model_name='businesspricingtier',
            name='produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_pricing', to='farmers.produce'),
        ),
        migrations.AddField(
            model_name='businessinvoice',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='business.businessprofile'),
        ),
        migrations.AddField(
            model_name='businessinvoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_invoice', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='businesspricingtier',
            index=models.Index(fields=['produce', 'min_quantity'], name='business_bu_produce_3bc513_idx'),
        ),
        migrations.AddIndex(
            model_name='businesspricingtier',
            index=models.Index(fields=['business'], name='business_bu_busines_f894dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businesspricingtier',
            unique_together={('business', 'produce', 'min_quantity', 'unit')},
        ),
        migrations.AddIndex(
            model_name='businessinvoice',
            index=models.Index(fields=['business'], name='business_bu_busines_840342_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinvoice',
            index=models.Index(fields=['status'], name='business_bu_status_e99e83_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinvoice',
            index=models.Index(fields=['due_date'], name='business_bu_due_dat_0a6413_idx'),
        ),
    ]
