# Generated by Django 4.2.23 on 2025-09-26 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_mixedbox_mixedboxitem_order_delivery_fee_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_renewal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_renewal_result',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='mixed_box',
            field=models.ForeignKey(blank=True, help_text='Box subscribed to, if box-based', null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.mixedbox'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='skip_next',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Optional discount when used for subscriptions', max_digits=5),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='period',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=20),
        ),
    ]
