# Generated by Django 4.2.23 on 2025-08-08 21:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0004_produce_image'),
        ('orders', '0002_remove_order_total_price_order_total_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_preferences', models.JSONField(default=dict, help_text='Delivery time preferences, address details')),
                ('preferred_delivery_time', models.CharField(blank=True, help_text='Preferred delivery time slot', max_length=50)),
                ('delivery_instructions', models.TextField(blank=True, help_text='Special delivery instructions')),
                ('dietary_preferences', models.TextField(blank=True, help_text='Dietary restrictions, allergies, preferences')),
                ('organic_preference', models.BooleanField(default=False, help_text='Prefer organic produce')),
                ('local_preference', models.BooleanField(default=True, help_text='Prefer locally grown produce')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('favorite_produce_types', models.JSONField(default=list, help_text='List of favorite produce categories')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_farmers', models.ManyToManyField(blank=True, related_name='favorite_consumers', to='farmers.farmerprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consumers_profile',
            },
        ),
        migrations.CreateModel(
            name='ConsumerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_produce_types', models.JSONField(default=list, help_text='Preferred produce types')),
                ('excluded_produce_types', models.JSONField(default=list, help_text='Produce types to avoid')),
                ('preferred_quantities', models.JSONField(default=dict, help_text='Preferred quantities for different produce')),
                ('bulk_ordering_preference', models.BooleanField(default=False, help_text='Prefer bulk ordering')),
                ('price_range_preference', models.CharField(blank=True, help_text='Preferred price range', max_length=50)),
                ('discount_preference', models.BooleanField(default=True, help_text='Prefer discounted items')),
                ('subscription_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('subscription_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notification_channels', models.JSONField(default=list, help_text='Preferred notification channels')),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily digest'), ('weekly', 'Weekly digest')], default='immediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='consumers.consumerprofile')),
            ],
            options={
                'db_table': 'consumers_preference',
            },
        ),
        migrations.CreateModel(
            name='ConsumerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_spending', models.JSONField(default=dict, help_text='Monthly spending breakdown')),
                ('yearly_spending', models.JSONField(default=dict, help_text='Yearly spending breakdown')),
                ('order_frequency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Orders per month', max_digits=5)),
                ('average_order_size', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('top_produce_categories', models.JSONField(default=list, help_text='Most ordered produce categories')),
                ('seasonal_preferences', models.JSONField(default=dict, help_text='Seasonal produce preferences')),
                ('preferred_delivery_days', models.JSONField(default=list, help_text='Most common delivery days')),
                ('delivery_success_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('total_logins', models.PositiveIntegerField(default=0)),
                ('days_since_last_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='consumers.consumerprofile')),
            ],
            options={
                'verbose_name_plural': 'Consumer analytics',
                'db_table': 'consumers_analytics',
            },
        ),
        migrations.CreateModel(
            name='ConsumerWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, help_text='Notes about this wishlist item')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True, help_text='Whether the produce is currently available')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='consumers.consumerprofile')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_consumers', to='farmers.produce')),
            ],
            options={
                'db_table': 'consumers_wishlist',
                'indexes': [models.Index(fields=['consumer'], name='consumers_w_consume_0150bd_idx'), models.Index(fields=['produce'], name='consumers_w_produce_47db34_idx'), models.Index(fields=['added_at'], name='consumers_w_added_a_baba21_idx')],
                'unique_together': {('consumer', 'produce')},
            },
        ),
        migrations.CreateModel(
            name='ConsumerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(help_text='Detailed review of the produce')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Whether this review is from a verified purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='consumers.consumerprofile')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_reviews', to='farmers.produce')),
            ],
            options={
                'db_table': 'consumers_review',
                'indexes': [models.Index(fields=['consumer'], name='consumers_r_consume_f6a9d0_idx'), models.Index(fields=['produce'], name='consumers_r_produce_a16b0f_idx'), models.Index(fields=['rating'], name='consumers_r_rating_541e8a_idx'), models.Index(fields=['created_at'], name='consumers_r_created_65539d_idx')],
                'unique_together': {('consumer', 'produce')},
            },
        ),
        migrations.AddIndex(
            model_name='consumerprofile',
            index=models.Index(fields=['user'], name='consumers_p_user_id_5f477a_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerprofile',
            index=models.Index(fields=['total_spent'], name='consumers_p_total_s_ab68bc_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerprofile',
            index=models.Index(fields=['total_orders'], name='consumers_p_total_o_def6aa_idx'),
        ),
    ]
