# Generated by Django 4.2.23 on 2025-09-26 12:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_farmerprofile_total_earnings_and_more'),
        ('deliveries', '__latest__'),
        ('inventory', '0001_initial'),
        ('orders', '0002_remove_order_total_price_order_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixedBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MixedBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='deliveries.deliverywindow'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('PARTIALLY_REFUNDED', 'Partially refunded'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=24),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dry_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_substituted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shortage_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='substituted_product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mixed_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.mixedbox'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('produce__isnull', False), ('mixed_box__isnull', False), ('dry_variant__isnull', False), _connector='OR'), name='order_item_requires_one_source'),
        ),
        migrations.AddField(
            model_name='mixedboxitem',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.mixedbox'),
        ),
        migrations.AddField(
            model_name='mixedboxitem',
            name='produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_items', to='farmers.produce'),
        ),
        migrations.AddIndex(
            model_name='mixedbox',
            index=models.Index(fields=['is_active'], name='orders_mixe_is_acti_f64014_idx'),
        ),
        migrations.AddIndex(
            model_name='mixedbox',
            index=models.Index(fields=['size'], name='orders_mixe_size_2e0095_idx'),
        ),
        migrations.AddIndex(
            model_name='mixedboxitem',
            index=models.Index(fields=['box'], name='orders_mixe_box_id_bda813_idx'),
        ),
        migrations.AddIndex(
            model_name='mixedboxitem',
            index=models.Index(fields=['produce'], name='orders_mixe_produce_30e8c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mixedboxitem',
            unique_together={('box', 'produce')},
        ),
    ]
