# Generated by Django 4.2.23 on 2025-09-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_delivered_at_alter_delivery_distributor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('batch_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LOCKED', 'Locked'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('cutoff_at', models.DateTimeField(blank=True, help_text='After this time, orders fall into the next batch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('days_of_week', models.JSONField(default=list, help_text='List of integers 0-6 (Mon-Sun)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cutoff_time', models.TimeField(help_text='Time of day cutoff to lock batches')),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payout_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payout_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid')], default='UNPAID', max_length=20),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['payout_status'], name='deliveries__payout__217597_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverywindow',
            index=models.Index(fields=['active'], name='deliveries__active_1d9afb_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverywindow',
            index=models.Index(fields=['zone'], name='deliveries__zone_df554b_idx'),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='deliveries.deliverywindow'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='deliveries.deliverybatch'),
        ),
        migrations.AddIndex(
            model_name='deliverybatch',
            index=models.Index(fields=['batch_date'], name='deliveries__batch_d_556266_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverybatch',
            index=models.Index(fields=['status'], name='deliveries__status_2a1373_idx'),
        ),
    ]
